version: "3.8"

services:
  server:
    image: olimpiad/server:v1
    networks:
      - api-internal
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
    environment:
      NODE_ENV: development
      PORT: 3000
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: denisa
      PGDATABASE: cloud-project
      PGPORT: 5432
  postgres:
    networks:
      - api-internal
      - db-internal
    image: postgres:12
    volumes:
      - ./db_config/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cloud-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denisa
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db-internal
    depends_on:
      - postgres
volumes:
  postgresdata:
networks:
  api-internal:
  db-internal:
